
iknsa_blog_post:
    resource: "@IKNSABlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

iknsa_blog_comment:
    resource: "@IKNSABlogBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

iknsa_blog_homepage:
    path:     /
    defaults: { _controller: IKNSABlogBundle:Blog:index }

blog_api_post:
  path:     /api/post
  defaults: { _controller: "IKNSABlogBundle:Post:apiIndex" }


blog_api_comment_post:
  path:     /api/post/{id}
  defaults: { _controller: "IKNSABlogBundle:Post:apiShow" }

  
