<?php

namespace IKNSA\BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCommentsForPost($post)
    {
        return $this->getEntityManager()->createQuery("SELECT c FROM IKNSABlogBundle:Comment c JOIN c.post p WHERE p = $post ORDER BY c.id DESC")
		->getResult();
 	}
}
