iknsa_post:
    resource: "@IKNSAPostBundle/Resources/config/routing.yml"
    prefix:   /

iknsa_comment:
    resource: "@IKNSAPostBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

iknsa_blog:
    resource: "@IKNSABlogBundle/Resources/config/routing.yml"
    prefix:   /

iknsa_app:
    resource: "@IKNSAAppBundle/Resources/config/routing.yml"
    prefix:   /

